
#  -------HARSHAD NUMBER

# num=int(input("enter the number"))
# i=1
# while i==1:
#     a=num%10
#     b=(num//10)%10
#     c=(num//10)//10
#     d=a+b+c
#     if num%d==0:
#         print("it is a harshad number")  
#     else:
#         print("it not harshad number")  
#     i=i+1



#                  PRIME NUMBER

# user=int(input("enter the number"))
# i=1
# count=0
# while i<=user:
#     if user%i==0:
#         count=count+1
#     i=i+1
# if count==2:
#     print("it is prime number")  
# else:
#     print("it is not prim number")






e            # PATTERN CODE TRANGLE

# num=int(input("enter the number"))
# colum=1
# while colum<=num:
#     row=1
#     while row<=colum:
#         print(row,end=" ")
#         row=row+1
#     k=colum
#     while k>0:
#         print(k,end=" ")
#         k=k-1
#     print()
#     colum=colum+1






